# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ks5ecvqlGLWik0UlTBGNoRkyMWeUobnJ
"""

import pandas as pd


data = {
    "Student_ID": [1,1,1,2,2,3,3,3,3,4,4],
    "Attempt_Number": [1,2,3,1,2,1,2,3,4,1,2],
    "Score": [60,70,80,55,65,50,60,70,85,58,68]
}


df = pd.DataFrame(data)


df

print("Dataset Info:")
df.info()


print("\nMissing Values:")
df.isnull().sum()

attempts_per_student = df.groupby("Student_ID")["Attempt_Number"].max()

print("Attempts per Student:")
attempts_per_student

avg_score_attempt = df.groupby("Attempt_Number")["Score"].mean()

print("Average Score per Attempt:")
avg_score_attempt

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
attempts_per_student.plot(kind='bar', color='skyblue')
plt.title("Quiz Attempts per Student")
plt.xlabel("Student ID")
plt.ylabel("Number of Attempts")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
plt.plot(avg_score_attempt.index, avg_score_attempt.values, marker='o', color='green')
plt.title("Average Score vs Attempt Number")
plt.xlabel("Attempt Number")
plt.ylabel("Average Score")
plt.grid(True)
plt.tight_layout()
plt.show()

correlation = df["Attempt_Number"].corr(df["Score"])
print("Correlation between Attempt Number and Score:", round(correlation,2))

print("Conclusion:")
print("Students generally improve their scores with multiple quiz attempts.")
